# Generated by Django 4.0.4 on 2022-05-18 07:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_car_body_style_alter_car_cart_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_photo',
            field=models.ImageField(upload_to='cars_images', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_photo_1',
            field=models.ImageField(blank=True, upload_to='cars_images', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_photo_2',
            field=models.ImageField(blank=True, upload_to='cars_images', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_photo_3',
            field=models.ImageField(blank=True, upload_to='cars_images', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_photo_4',
            field=models.ImageField(blank=True, upload_to='cars_images', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg'])]),
        ),
    ]
